In [1]:
# Useful additional packages
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

In [2]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

<br>
<br>
<br>

# Single-Qubit Gates


In [3]:
q = QuantumRegister(1)

<br>
<br>

## u gates

$$u3(θ,ϕ,λ)=U(θ,ϕ,λ)$$

In [5]:
qc = QuantumCircuit(q)
qc.u3(pi/2,pi/2,pi/2,q)
qc.draw()

┌────────────────────┐
q0_0: ┤ U3(pi/2,pi/2,pi/2) ├
      └────────────────────┘

In [6]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 7.07106781e-01+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 4.32978028e-17+7.07106781e-01j, -7.07106781e-01+8.65956056e-17j]])

In [7]:
qc = QuantumCircuit(q)
qc.u2(pi/2,pi/2,q)
qc.draw()

┌───────────────┐
q0_0: ┤ U2(pi/2,pi/2) ├
      └───────────────┘

In [8]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 7.07106781e-01+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 4.32978028e-17+7.07106781e-01j, -7.07106781e-01+8.65956056e-17j]])

In [9]:
qc = QuantumCircuit(q)
qc.u1(pi/2,q)
qc.draw()

┌──────────┐
q0_0: ┤ U1(pi/2) ├
      └──────────┘

In [10]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

<br>
<br>

## Identity gate

$$  Id=u0(1). $$

In [11]:
c = QuantumCircuit(q)
qc.id(q)
qc.draw()

┌──────────┐┌───┐
q0_0: ┤ U1(pi/2) ├┤ I ├
      └──────────┘└───┘

In [12]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

<br>
<br>

## Pauli gates


### X: bit-flip gate

In [13]:
qc = QuantumCircuit(q)
qc.x(q)
qc.draw()

┌───┐
q0_0: ┤ X ├
      └───┘

In [14]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.+0.0000000e+00j, 1.-1.2246468e-16j],
       [1.+0.0000000e+00j, 0.+0.0000000e+00j]])

<br>

### Y: bit- and phase-flip gate


In [15]:
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q0_0: ┤ Y ├
      └───┘

In [16]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.000000e+00+0.j, -6.123234e-17-1.j],
       [ 6.123234e-17+1.j,  0.000000e+00+0.j]])

<br>

### Z: phase-flip gate


In [17]:
qc = QuantumCircuit(q)
qc.z(q)
qc.draw()

┌───┐
q0_0: ┤ Z ├
      └───┘

In [18]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.+0.0000000e+00j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])

<br>
<br>

## Clifford gates


### Hadamard gate


In [19]:
qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

┌───┐
q0_0: ┤ H ├
      └───┘

In [20]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.70710678+0.00000000e+00j,  0.70710678-8.65956056e-17j],
       [ 0.70710678+0.00000000e+00j, -0.70710678+8.65956056e-17j]])

<br>

### $S$ (or, $\sqrt(Z)$ phase) gate


In [21]:
qc = QuantumCircuit(q)
qc.s(q)
qc.draw()

┌───┐
q0_0: ┤ S ├
      └───┘

In [22]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

<br>

### $S^{\dagger}$ (or, conjugate of, $\sqrt(Z)$ phase) gate


In [23]:
qc = QuantumCircuit(q)
qc.sdg(q)
qc.draw()

┌─────┐
q0_0: ┤ SDG ├
      └─────┘

In [24]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17-1.j]])

<br>
<br>

## $C3$ gates


### $T$ (or, $\sqrt(S)$ phase) gate



In [25]:
qc = QuantumCircuit(q)
qc.t(q)
qc.draw()

┌───┐
q0_0: ┤ T ├
      └───┘

In [26]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

<br>

### $T^{\dagger}$ (or, conjugate of, $\sqrt{S}$ phase) gate


In [27]:
qc = QuantumCircuit(q)
qc.tdg(q)
qc.draw()

┌─────┐
q0_0: ┤ TDG ├
      └─────┘

In [28]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j]])

<br>
<br>

## Standard Rotations


### Rotation around X-axis



In [29]:
qc = QuantumCircuit(q)
qc.rx(pi/2,q)
qc.draw()

┌──────────┐
q0_0: ┤ RX(pi/2) ├
      └──────────┘

In [30]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 7.07106781e-01+0.j        , -4.32978028e-17-0.70710678j],
       [ 4.32978028e-17-0.70710678j,  7.07106781e-01+0.j        ]])

### Rotation around Y-axis

In [31]:
qc = QuantumCircuit(q)
qc.ry(pi/2,q)
qc.draw()

┌──────────┐
q0_0: ┤ RY(pi/2) ├
      └──────────┘

In [32]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.70710678+0.j, -0.70710678+0.j],
       [ 0.70710678+0.j,  0.70710678+0.j]])

### Rotation around Z-axis

In [33]:
qc = QuantumCircuit(q)
qc.rz(pi/2,q)
qc.draw()

┌──────────┐
q0_0: ┤ RZ(pi/2) ├
      └──────────┘

In [34]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j]])

<br>
<br>
<br>

# Multi-Qubit Gates

## Two-qubit gates


In [37]:
q = QuantumRegister(2)

<br>
<br>

## Controlled Pauli Gates

### Controlled-X (or, controlled-NOT) gate

In [38]:
qc = QuantumCircuit(q)
qc.cx(q[0],q[1])
qc.draw()

q18_0: ──■──
       ┌─┴─┐
q18_1: ┤ X ├
       └───┘

<br>

### Controlled Y gate

In [39]:
qc = QuantumCircuit(q)
qc.cy(q[0],q[1])
qc.draw()

q18_0: ──■──
       ┌─┴─┐
q18_1: ┤ Y ├
       └───┘

In [40]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 0.000000e+00+0.j,
        6.123234e-17-1.j],
       [0.000000e+00+0.j, 0.000000e+00+0.j, 1.000000e+00+0.j,
        0.000000e+00+0.j],
       [0.000000e+00+0.j, 6.123234e-17+1.j, 0.000000e+00+0.j,
        0.000000e+00+0.j]])

<br>

### Controlled Z gate

In [41]:
qc = QuantumCircuit(q)
qc.cz(q[0],q[1])
qc.draw()

q18_0: ─■─
        │ 
q18_1: ─■─

In [42]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.-6.1232340e-17j,  0.+0.0000000e+00j,  0.+0.0000000e+00j,
         0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j,  1.-6.1232340e-17j,  0.+0.0000000e+00j,
         0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j,  0.+0.0000000e+00j,  1.-1.8369702e-16j,
         0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j,  0.+0.0000000e+00j,  0.+0.0000000e+00j,
        -1.+1.8369702e-16j]])

<br>

### Controlled Hadamard gate

In [43]:
qc = QuantumCircuit(q)
qc.ch(q[0],q[1])
qc.draw()

q18_0: ──■──
       ┌─┴─┐
q18_1: ┤ H ├
       └───┘

In [44]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.        -1.11022302e-16j,  0.        +0.00000000e+00j,
         0.        +0.00000000e+00j,  0.        +0.00000000e+00j],
       [ 0.        +0.00000000e+00j,  0.70710678-5.55111512e-17j,
         0.        +0.00000000e+00j,  0.70710678-2.22044605e-16j],
       [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         1.        -2.27765794e-16j,  0.        +0.00000000e+00j],
       [ 0.        +0.00000000e+00j,  0.70710678+5.55111512e-17j,
         0.        +0.00000000e+00j, -0.70710678+1.66533454e-16j]])

<br>
<br>

## Controlled rotation gates

### Controlled rotation around Z-axis

In [45]:
qc = QuantumCircuit(q)
qc.crz(pi/2,q[0],q[1])
qc.draw()

q18_0: ─────■──────
       ┌────┴─────┐
q18_1: ┤ RZ(pi/2) ├
       └──────────┘

In [46]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.70710678+0.70710678j]])

<br>

### Controlled phase rotation


In [47]:
qc = QuantumCircuit(q)
qc.cu1(pi/2,q[0], q[1])
qc.draw()

q18_0: ─■─────
        │pi/2 
q18_1: ─■─────

In [48]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.00000000e+00+0.j, 0.00000000e+00+0.j, 0.00000000e+00+0.j,
        0.00000000e+00+0.j],
       [0.00000000e+00+0.j, 1.00000000e+00+0.j, 0.00000000e+00+0.j,
        0.00000000e+00+0.j],
       [0.00000000e+00+0.j, 0.00000000e+00+0.j, 1.00000000e+00+0.j,
        0.00000000e+00+0.j],
       [0.00000000e+00+0.j, 0.00000000e+00+0.j, 0.00000000e+00+0.j,
        2.22044605e-16+1.j]])

<br>

### Controlled u3 rotation



In [49]:
qc = QuantumCircuit(q)
qc.cu3(pi/2, pi/2, pi/2, q[0], q[1])
qc.draw()

q18_0: ──────────■───────────
       ┌─────────┴──────────┐
q18_1: ┤ U3(pi/2,pi/2,pi/2) ├
       └────────────────────┘

In [50]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  7.07106781e-01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  4.32978028e-17+7.07106781e-01j,
         0.00000000e+00+0.00000000e+00j, -7.07106781e-01+8.65956056e-17j]])

<br>

### SWAP gate



In [51]:
qc = QuantumCircuit(q)
qc.swap(q[0], q[1])
qc.draw()

q18_0: ─X─
        │ 
q18_1: ─X─

In [52]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])